### ISSUE TITLE
if sample does not have site(e.g. controls) pipeUtils fails to produce heatmap

### ISSUE THREAD

**Issue by anatolydryga** [BushmanLab/genomicHeatmapMaker#1]
what should be preferred behavior:
1. failure
2. removing controls just before the heatmap
3. ?...

**Comment by anatolydryga** [comment]
we can check if sample has sites with getUniqueSiteCounts()

**Comment by esherm** [comment]
I would say just remove the sample from the analysis and output a warning message in the R code so that nobody ends up spending hours debugging a heat map where a control was omitted
